version: '2'
services:
    rabbit1:
        image: "rabbitmq:3-management"
        hostname: "rabbit1"
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "hdk"
            RABBITMQ_DEFAULT_PASS: "1"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
            - "5672:5672"
        labels:
            NAME: "rabbitmq1"
        volumes:
            - "./data:/var/lib/rabbitmq/mnesia/rabbit@rabbit1"

